name: cd
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cd.yml'
      - 'packages/**/.nginx'
      - 'packages/**/src'
      - 'packages/**/package.json'
      - 'packages/**/babel.config.js'
      - 'packages/**/next.config.js'
      - 'Dockerfile'
      - '!packages/**/*.spec.*'
      - '!packages/**/*.snap'

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: docker build -t registry.heroku.com/calculator-app-demo/web .

    - name: Login to Heroku Container registry
      run: heroku container:login

    - name: Push container
      run: docker push registry.heroku.com/calculator-app-demo/web

    - name: Release container
      run: heroku container:release web --app calculator-app-demo
