name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  check:
    name: Lint, test and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.11.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get yarn cache dir
      id: yarn-cache-output
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Restore yarn global cache
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-output.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Restore node_modules cache
      uses: actions/cache@v1
      id: node-modules-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install packages
      run: yarn --frozen-lockfile

    - name: ESLint
      run: (cd packages/app && yarn lint)

    - name: Run unit tests
      run: (cd packages/app && yarn test)

    - name: Build the app
      run: (cd packages/app && yarn build)
